"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
const client_1 = require("@prisma/client");
const bcrypt = __importStar(require("bcryptjs"));
const prisma = new client_1.PrismaClient();
async function main() {
    console.log("Starting seeding process...");
    // 1. Clean existing data
    await prisma.activityLog.deleteMany({});
    await prisma.supplierPayment.deleteMany({});
    await prisma.customerCreditPayment.deleteMany({});
    await prisma.expense.deleteMany({});
    await prisma.stockMovement.deleteMany({});
    await prisma.warrantyClaim.deleteMany({});
    await prisma.saleItem.deleteMany({});
    await prisma.sale.deleteMany({});
    await prisma.repairJob.deleteMany({});
    await prisma.purchaseItem.deleteMany({});
    await prisma.purchaseOrder.deleteMany({});
    await prisma.branchStock.deleteMany({});
    await prisma.product.deleteMany({});
    await prisma.user.deleteMany({});
    await prisma.branch.deleteMany({});
    await prisma.category.deleteMany({});
    await prisma.brand.deleteMany({});
    await prisma.customer.deleteMany({});
    await prisma.supplier.deleteMany({});
    // 2. Create Branches
    const showroom = await prisma.branch.create({
        data: {
            name: "Default Store",
            address: "123 Electronics Avenue, City Center",
            phone: "+1-555-0100"
        }
    });
    const warehouse = await prisma.branch.create({
        data: {
            name: "Central Warehouse",
            address: "45 Industrial Zone, Outer Suburb",
            phone: "+1-555-0200"
        }
    });
    console.log("Branches seeded.");
    // 3. Create Users
    const salt = await bcrypt.genSalt(10);
    const adminPassword = await bcrypt.hash("admin123", salt);
    const staffPassword = await bcrypt.hash("staff123", salt);
    const superadminPassword = await bcrypt.hash("superadmin123", salt);
    const owner = await prisma.user.create({
        data: {
            name: "Owner John",
            username: "admin",
            passwordHash: adminPassword,
            role: "OWNER",
            email: "owner@electronics.com",
            phone: "+1-555-1111",
            branchId: showroom.id
        }
    });
    const superadmin = await prisma.user.create({
        data: {
            name: "Super Admin",
            username: "superadmin",
            passwordHash: superadminPassword,
            role: "SUPER_ADMIN",
            email: "superadmin@shop.com",
            phone: null,
            branchId: showroom.id
        }
    });
    const manager = await prisma.user.create({
        data: {
            name: "Manager Sarah",
            username: "manager",
            passwordHash: staffPassword,
            role: "MANAGER",
            email: "manager@electronics.com",
            phone: "+1-555-2222",
            branchId: showroom.id
        }
    });
    const cashier = await prisma.user.create({
        data: {
            name: "Cashier Alice",
            username: "cashier",
            passwordHash: staffPassword,
            role: "CASHIER",
            email: "cashier@electronics.com",
            phone: "+1-555-3333",
            branchId: showroom.id
        }
    });
    const warehouseStaff = await prisma.user.create({
        data: {
            name: "Warehouse Bob",
            username: "warehouse",
            passwordHash: staffPassword,
            role: "WAREHOUSE",
            email: "warehouse@electronics.com",
            phone: "+1-555-4444",
            branchId: warehouse.id
        }
    });
    const technician = await prisma.user.create({
        data: {
            name: "Technician Dave",
            username: "tech",
            passwordHash: staffPassword,
            role: "TECHNICIAN",
            email: "tech@electronics.com",
            phone: "+1-555-5555",
            branchId: showroom.id
        }
    });
    console.log("Users seeded.");
    // 4. Create Categories
    const categoriesData = [
        "Smartphones", "Tablets", "Laptops", "Monitors", "TVs", "Accessories", "Gaming",
        "Audio", "Cameras", "Wearables", "Networking", "Storage", "Components", "Printers",
        "Home Appliances", "Smart Home", "Power Banks", "Chargers", "Cables", "Cases & Covers"
    ];
    const categoriesMap = {};
    for (const catName of categoriesData) {
        const cat = await prisma.category.create({ data: { name: catName } });
        categoriesMap[catName] = cat.id;
    }
    // 5. Create Brands
    const brandsData = [
        "Apple", "Samsung", "Xiaomi", "Dell", "HP", "Sony", "Lenovo",
        "Google", "OnePlus", "Nothing", "ASUS", "MSI", "Acer", "LG",
        "JBL", "Bose", "Sennheiser", "Anker", "Logitech", "Razer",
        "Nikon", "Canon", "GoPro", "Garmin", "Fitbit", "TP-Link",
        "Western Digital", "Seagate", "Corsair", "HyperX", "SteelSeries",
        "NVIDIA", "AMD", "Intel", "Epson", "Brother", "Dyson",
        "Philips", "Huawei", "OPPO", "Vivo", "Realme"
    ];
    const brandsMap = {};
    for (const brandName of brandsData) {
        const br = await prisma.brand.create({ data: { name: brandName } });
        brandsMap[brandName] = br.id;
    }
    console.log("Categories and Brands seeded.");
    // 6. Create Suppliers
    const supplierA = await prisma.supplier.create({
        data: {
            company: "Apex Distributors",
            contactPerson: "Mark Apex",
            phone: "+1-555-6666",
            email: "orders@apexdistributors.com",
            address: "10 Wholesale Blvd"
        }
    });
    const supplierB = await prisma.supplier.create({
        data: {
            company: "Silicon Supply Co",
            contactPerson: "Jennifer Silicon",
            phone: "+1-555-7777",
            email: "sales@siliconsupply.com",
            address: "22 Chip Plaza"
        }
    });
    console.log("Suppliers seeded.");
    // 7. Create Customers
    const customer1 = await prisma.customer.create({
        data: {
            name: "Michael Green",
            phone: "5551234567",
            email: "michael@green.com",
            address: "99 Maple Lane",
            rewardPoints: 120,
            creditLimit: 1000.0,
            creditBalance: 150.0 // Has outstanding balance
        }
    });
    const customer2 = await prisma.customer.create({
        data: {
            name: "Emily White",
            phone: "5559876543",
            email: "emily@white.com",
            address: "42 Birch Circle",
            rewardPoints: 50,
            creditLimit: 500.0,
            creditBalance: 0.0
        }
    });
    console.log("Customers seeded.");
    // 8. Create Products
    const products = [
        // SMARTPHONES
        {
            name: "iPhone 15 Pro Max",
            sku: "AP-IP15PM-256G",
            barcode: "190199000123",
            qrCode: "QR-IP15PM",
            categoryId: categoriesMap["Smartphones"],
            brandId: brandsMap["Apple"],
            model: "iPhone 15 Pro Max",
            color: "Titanium Gray",
            storage: "256GB",
            ram: "8GB",
            processor: "A17 Pro",
            warrantyMonths: 12,
            supplierId: supplierA.id,
            purchasePrice: 950.00,
            sellingPrice: 1199.00,
            wholesalePrice: 1050.00,
            taxRate: 8.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_phone.jpg"]),
            description: "Latest flagship smartphone from Apple with Titanium design.",
            weight: 0.221,
            stockQuantity: 25,
            minStock: 5,
            type: "SINGLE"
        },
        {
            name: "iPhone 15",
            sku: "AP-IP15-128G",
            barcode: "190199000124",
            qrCode: "QR-IP15",
            categoryId: categoriesMap["Smartphones"],
            brandId: brandsMap["Apple"],
            model: "iPhone 15",
            color: "Blue",
            storage: "128GB",
            ram: "6GB",
            processor: "A16 Bionic",
            warrantyMonths: 12,
            supplierId: supplierA.id,
            purchasePrice: 650.00,
            sellingPrice: 799.00,
            wholesalePrice: 700.00,
            taxRate: 8.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_ip15.jpg"]),
            description: "Standard iPhone 15 with Dynamic Island.",
            weight: 0.171,
            stockQuantity: 30,
            minStock: 8,
            type: "SINGLE"
        },
        {
            name: "Galaxy S24 Ultra",
            sku: "SM-S24U-512G",
            barcode: "880609000456",
            qrCode: "QR-S24U",
            categoryId: categoriesMap["Smartphones"],
            brandId: brandsMap["Samsung"],
            model: "Galaxy S24 Ultra",
            color: "Phantom Black",
            storage: "512GB",
            ram: "12GB",
            processor: "Snapdragon 8 Gen 3",
            warrantyMonths: 24,
            supplierId: supplierA.id,
            purchasePrice: 1000.00,
            sellingPrice: 1299.00,
            wholesalePrice: 1150.00,
            taxRate: 8.0,
            discountRate: 5.0,
            images: JSON.stringify(["/placeholder_galaxy.jpg"]),
            description: "AI-powered flagship smartphone from Samsung with S-Pen.",
            weight: 0.233,
            stockQuantity: 15,
            minStock: 3,
            type: "SINGLE"
        },
        {
            name: "Galaxy S24+",
            sku: "SM-S24P-256G",
            barcode: "880609000457",
            qrCode: "QR-S24P",
            categoryId: categoriesMap["Smartphones"],
            brandId: brandsMap["Samsung"],
            model: "Galaxy S24+",
            color: "Cobalt Violet",
            storage: "256GB",
            ram: "8GB",
            processor: "Snapdragon 8 Gen 3",
            warrantyMonths: 24,
            supplierId: supplierA.id,
            purchasePrice: 750.00,
            sellingPrice: 999.00,
            wholesalePrice: 850.00,
            taxRate: 8.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_s24p.jpg"]),
            description: "Samsung Galaxy S24+ with AI features and stunning display.",
            weight: 0.196,
            stockQuantity: 20,
            minStock: 5,
            type: "SINGLE"
        },
        {
            name: "Galaxy A54 5G",
            sku: "SM-A54-128G",
            barcode: "880609000458",
            qrCode: "QR-A54",
            categoryId: categoriesMap["Smartphones"],
            brandId: brandsMap["Samsung"],
            model: "Galaxy A54 5G",
            color: "Awesome Graphite",
            storage: "128GB",
            ram: "6GB",
            processor: "Exynos 1380",
            warrantyMonths: 24,
            supplierId: supplierA.id,
            purchasePrice: 280.00,
            sellingPrice: 399.00,
            wholesalePrice: 320.00,
            taxRate: 8.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_a54.jpg"]),
            description: "Mid-range Samsung smartphone with great camera and battery.",
            weight: 0.202,
            stockQuantity: 35,
            minStock: 10,
            type: "SINGLE"
        },
        {
            name: "Pixel 8 Pro",
            sku: "GO-P8P-256G",
            barcode: "194253000654",
            qrCode: "QR-P8P",
            categoryId: categoriesMap["Smartphones"],
            brandId: brandsMap["Google"],
            model: "Pixel 8 Pro",
            color: "Obsidian",
            storage: "256GB",
            ram: "12GB",
            processor: "Google Tensor G3",
            warrantyMonths: 24,
            supplierId: supplierB.id,
            purchasePrice: 700.00,
            sellingPrice: 899.00,
            wholesalePrice: 780.00,
            taxRate: 8.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_p8p.jpg"]),
            description: "Google's AI-powered flagship with the best camera system.",
            weight: 0.213,
            stockQuantity: 18,
            minStock: 4,
            type: "SINGLE"
        },
        {
            name: "OnePlus 12",
            sku: "OP-12-256G",
            barcode: "692189000789",
            qrCode: "QR-OP12",
            categoryId: categoriesMap["Smartphones"],
            brandId: brandsMap["OnePlus"],
            model: "OnePlus 12",
            color: "Silky Black",
            storage: "256GB",
            ram: "12GB",
            processor: "Snapdragon 8 Gen 3",
            warrantyMonths: 12,
            supplierId: supplierB.id,
            purchasePrice: 500.00,
            sellingPrice: 649.00,
            wholesalePrice: 550.00,
            taxRate: 8.0,
            discountRate: 5.0,
            images: JSON.stringify(["/placeholder_op12.jpg"]),
            description: "Flagship killer with Hasselblad camera and 100W charging.",
            weight: 0.220,
            stockQuantity: 22,
            minStock: 5,
            type: "SINGLE"
        },
        {
            name: "Nothing Phone (2a)",
            sku: "NT-2A-256G",
            barcode: "860001000321",
            qrCode: "QR-NT2A",
            categoryId: categoriesMap["Smartphones"],
            brandId: brandsMap["Nothing"],
            model: "Phone (2a)",
            color: "Black",
            storage: "256GB",
            ram: "8GB",
            processor: "MediaTek Dimensity 7200 Pro",
            warrantyMonths: 12,
            supplierId: supplierB.id,
            purchasePrice: 220.00,
            sellingPrice: 319.00,
            wholesalePrice: 260.00,
            taxRate: 8.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_nt2a.jpg"]),
            description: "Unique Glyph interface smartphone with clean Nothing OS.",
            weight: 0.190,
            stockQuantity: 28,
            minStock: 8,
            type: "SINGLE"
        },
        {
            name: "Huawei Pura 70 Pro",
            sku: "HW-P70P-512G",
            barcode: "690123456789",
            qrCode: "QR-P70P",
            categoryId: categoriesMap["Smartphones"],
            brandId: brandsMap["Huawei"],
            model: "Pura 70 Pro",
            color: "Black",
            storage: "512GB",
            ram: "12GB",
            processor: "Kirin 9010",
            warrantyMonths: 24,
            supplierId: supplierA.id,
            purchasePrice: 680.00,
            sellingPrice: 899.00,
            wholesalePrice: 750.00,
            taxRate: 8.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_p70p.jpg"]),
            description: "Premium Huawei smartphone with advanced camera system.",
            weight: 0.220,
            stockQuantity: 12,
            minStock: 3,
            type: "SINGLE"
        },
        {
            name: "OPPO Find X7 Ultra",
            sku: "OP-FX7U-512G",
            barcode: "695123456789",
            qrCode: "QR-FX7U",
            categoryId: categoriesMap["Smartphones"],
            brandId: brandsMap["OPPO"],
            model: "Find X7 Ultra",
            color: "Black",
            storage: "512GB",
            ram: "16GB",
            processor: "Snapdragon 8 Gen 3",
            warrantyMonths: 12,
            supplierId: supplierA.id,
            purchasePrice: 700.00,
            sellingPrice: 949.00,
            wholesalePrice: 780.00,
            taxRate: 8.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_fx7u.jpg"]),
            description: "OPPO flagship with Hasselblad camera and 100W SUPERVOOC.",
            weight: 0.221,
            stockQuantity: 10,
            minStock: 2,
            type: "SINGLE"
        },
        {
            name: "Vivo X100 Pro",
            sku: "VV-X100P-512G",
            barcode: "693123456789",
            qrCode: "QR-X100P",
            categoryId: categoriesMap["Smartphones"],
            brandId: brandsMap["Vivo"],
            model: "X100 Pro",
            color: "Asteroid Black",
            storage: "512GB",
            ram: "16GB",
            processor: "MediaTek Dimensity 9300",
            warrantyMonths: 12,
            supplierId: supplierB.id,
            purchasePrice: 550.00,
            sellingPrice: 749.00,
            wholesalePrice: 620.00,
            taxRate: 8.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_x100p.jpg"]),
            description: "Vivo flagship with ZEISS optics and 5400mAh battery.",
            weight: 0.225,
            stockQuantity: 14,
            minStock: 3,
            type: "SINGLE"
        },
        {
            name: "Realme GT 5 Pro",
            sku: "RM-GT5P-256G",
            barcode: "694123456789",
            qrCode: "QR-GT5P",
            categoryId: categoriesMap["Smartphones"],
            brandId: brandsMap["Realme"],
            model: "GT 5 Pro",
            color: "Reddish Gold",
            storage: "256GB",
            ram: "12GB",
            processor: "Snapdragon 8 Gen 3",
            warrantyMonths: 12,
            supplierId: supplierB.id,
            purchasePrice: 380.00,
            sellingPrice: 499.00,
            wholesalePrice: 420.00,
            taxRate: 8.0,
            discountRate: 10.0,
            images: JSON.stringify(["/placeholder_gt5p.jpg"]),
            description: "Performance-focused flagship with 50MP Sony camera.",
            weight: 0.217,
            stockQuantity: 20,
            minStock: 5,
            type: "SINGLE"
        },
        // TABLETS
        {
            name: "iPad Pro 12.9 M2",
            sku: "AP-IPDP12-M2-256G",
            barcode: "190199000201",
            qrCode: "QR-IPDP12",
            categoryId: categoriesMap["Tablets"],
            brandId: brandsMap["Apple"],
            model: "iPad Pro 12.9 M2",
            color: "Space Gray",
            storage: "256GB",
            ram: "8GB",
            processor: "Apple M2",
            warrantyMonths: 12,
            supplierId: supplierA.id,
            purchasePrice: 900.00,
            sellingPrice: 1099.00,
            wholesalePrice: 980.00,
            taxRate: 8.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_ipdp.jpg"]),
            description: "Most powerful iPad with M2 chip and Liquid Retina XDR display.",
            weight: 0.682,
            stockQuantity: 15,
            minStock: 3,
            type: "SINGLE"
        },
        {
            name: "iPad Air M1",
            sku: "AP-IPDA-M1-256G",
            barcode: "190199000202",
            qrCode: "QR-IPDA",
            categoryId: categoriesMap["Tablets"],
            brandId: brandsMap["Apple"],
            model: "iPad Air M1",
            color: "Starlight",
            storage: "256GB",
            ram: "8GB",
            processor: "Apple M1",
            warrantyMonths: 12,
            supplierId: supplierA.id,
            purchasePrice: 500.00,
            sellingPrice: 649.00,
            wholesalePrice: 550.00,
            taxRate: 8.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_ipda.jpg"]),
            description: "Versatile iPad Air with M1 performance at an affordable price.",
            weight: 0.461,
            stockQuantity: 20,
            minStock: 5,
            type: "SINGLE"
        },
        {
            name: "Samsung Galaxy Tab S9 Ultra",
            sku: "SM-TAB-S9U-512G",
            barcode: "880609000501",
            qrCode: "QR-TAB-S9U",
            categoryId: categoriesMap["Tablets"],
            brandId: brandsMap["Samsung"],
            model: "Galaxy Tab S9 Ultra",
            color: "Graphite",
            storage: "512GB",
            ram: "12GB",
            processor: "Snapdragon 8 Gen 2",
            warrantyMonths: 24,
            supplierId: supplierA.id,
            purchasePrice: 850.00,
            sellingPrice: 1099.00,
            wholesalePrice: 920.00,
            taxRate: 8.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_tabs9u.jpg"]),
            description: "Samsung's largest and most powerful tablet with S Pen included.",
            weight: 0.732,
            stockQuantity: 12,
            minStock: 3,
            type: "SINGLE"
        },
        {
            name: "Xiaomi Pad 6",
            sku: "XI-PAD6-256G",
            barcode: "693123456701",
            qrCode: "QR-PAD6",
            categoryId: categoriesMap["Tablets"],
            brandId: brandsMap["Xiaomi"],
            model: "Pad 6",
            color: "Gravity Gray",
            storage: "256GB",
            ram: "8GB",
            processor: "Snapdragon 870",
            warrantyMonths: 12,
            supplierId: supplierB.id,
            purchasePrice: 280.00,
            sellingPrice: 379.00,
            wholesalePrice: 320.00,
            taxRate: 8.0,
            discountRate: 5.0,
            images: JSON.stringify(["/placeholder_pad6.jpg"]),
            description: "Value tablet with 144Hz display and great performance.",
            weight: 0.490,
            stockQuantity: 25,
            minStock: 8,
            type: "SINGLE"
        },
        // LAPTOPS
        {
            name: "Dell XPS 15 9530",
            sku: "DE-XPS15-I9-32G",
            barcode: "884116000789",
            qrCode: "QR-XPS15",
            categoryId: categoriesMap["Laptops"],
            brandId: brandsMap["Dell"],
            model: "XPS 15 9530",
            color: "Platinum Silver",
            storage: "1TB SSD",
            ram: "32GB",
            processor: "Intel Core i9-13900H",
            warrantyMonths: 12,
            supplierId: supplierB.id,
            purchasePrice: 1800.00,
            sellingPrice: 2299.00,
            wholesalePrice: 2000.00,
            taxRate: 10.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_xps.jpg"]),
            description: "High-performance creator laptop with InfinityEdge display.",
            weight: 1.92,
            stockQuantity: 8,
            minStock: 2,
            type: "SINGLE"
        },
        {
            name: "MacBook Pro 16 M3 Max",
            sku: "AP-MBP16-M3M-36G",
            barcode: "190199000301",
            qrCode: "QR-MBP16",
            categoryId: categoriesMap["Laptops"],
            brandId: brandsMap["Apple"],
            model: "MacBook Pro 16 M3 Max",
            color: "Space Black",
            storage: "1TB SSD",
            ram: "36GB",
            processor: "Apple M3 Max",
            warrantyMonths: 12,
            supplierId: supplierA.id,
            purchasePrice: 2800.00,
            sellingPrice: 3499.00,
            wholesalePrice: 3000.00,
            taxRate: 10.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_mbp16.jpg"]),
            description: "Most powerful MacBook Pro for professionals and creators.",
            weight: 2.14,
            stockQuantity: 6,
            minStock: 2,
            type: "SINGLE"
        },
        {
            name: "MacBook Air 15 M3",
            sku: "AP-MBA15-M3-16G",
            barcode: "190199000302",
            qrCode: "QR-MBA15",
            categoryId: categoriesMap["Laptops"],
            brandId: brandsMap["Apple"],
            model: "MacBook Air 15 M3",
            color: "Midnight",
            storage: "512GB SSD",
            ram: "16GB",
            processor: "Apple M3",
            warrantyMonths: 12,
            supplierId: supplierA.id,
            purchasePrice: 1100.00,
            sellingPrice: 1299.00,
            wholesalePrice: 1180.00,
            taxRate: 10.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_mba15.jpg"]),
            description: "Thin and light MacBook Air with 15.3-inch display.",
            weight: 1.51,
            stockQuantity: 12,
            minStock: 3,
            type: "SINGLE"
        },
        {
            name: "HP Spectre x360 14",
            sku: "HP-SPX360-I7-16G",
            barcode: "195201000401",
            qrCode: "QR-SPX360",
            categoryId: categoriesMap["Laptops"],
            brandId: brandsMap["HP"],
            model: "Spectre x360 14",
            color: "Nightfall Black",
            storage: "1TB SSD",
            ram: "16GB",
            processor: "Intel Core i7-1355U",
            warrantyMonths: 12,
            supplierId: supplierB.id,
            purchasePrice: 1100.00,
            sellingPrice: 1399.00,
            wholesalePrice: 1200.00,
            taxRate: 10.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_spx360.jpg"]),
            description: "Premium 2-in-1 convertible laptop with OLED display.",
            weight: 1.36,
            stockQuantity: 10,
            minStock: 3,
            type: "SINGLE"
        },
        {
            name: "ASUS ROG Strix G16",
            sku: "AS-ROG-G16-I9-4080",
            barcode: "471101000501",
            qrCode: "QR-ROGG16",
            categoryId: categoriesMap["Laptops"],
            brandId: brandsMap["ASUS"],
            model: "ROG Strix G16",
            color: "Eclipse Gray",
            storage: "1TB SSD",
            ram: "32GB",
            processor: "Intel Core i9-14900HX",
            warrantyMonths: 12,
            supplierId: supplierB.id,
            purchasePrice: 1800.00,
            sellingPrice: 2199.00,
            wholesalePrice: 1900.00,
            taxRate: 10.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_rogg16.jpg"]),
            description: "High-performance gaming laptop with RTX 4080 GPU.",
            weight: 2.50,
            stockQuantity: 8,
            minStock: 2,
            type: "SINGLE"
        },
        {
            name: "Lenovo ThinkPad X1 Carbon Gen 11",
            sku: "LN-X1C-G11-I7-16G",
            barcode: "195301000601",
            qrCode: "QR-X1C",
            categoryId: categoriesMap["Laptops"],
            brandId: brandsMap["Lenovo"],
            model: "ThinkPad X1 Carbon Gen 11",
            color: "Black",
            storage: "512GB SSD",
            ram: "16GB",
            processor: "Intel Core i7-1365U",
            warrantyMonths: 12,
            supplierId: supplierB.id,
            purchasePrice: 1200.00,
            sellingPrice: 1549.00,
            wholesalePrice: 1300.00,
            taxRate: 10.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_x1c.jpg"]),
            description: "Ultimate business ultrabook with legendary ThinkPad quality.",
            weight: 1.12,
            stockQuantity: 10,
            minStock: 3,
            type: "SINGLE"
        },
        {
            name: "MSI Raider GE78 HX",
            sku: "MS-RAIDER-GE78-I9-4090",
            barcode: "471910000701",
            qrCode: "QR-RAIDER",
            categoryId: categoriesMap["Laptops"],
            brandId: brandsMap["MSI"],
            model: "Raider GE78 HX",
            color: "Core Black",
            storage: "2TB SSD",
            ram: "64GB",
            processor: "Intel Core i9-14900HX",
            warrantyMonths: 12,
            supplierId: supplierB.id,
            purchasePrice: 2500.00,
            sellingPrice: 3099.00,
            wholesalePrice: 2700.00,
            taxRate: 10.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_raider.jpg"]),
            description: "Top-tier gaming laptop with RTX 4090 and Mini LED display.",
            weight: 3.10,
            stockQuantity: 5,
            minStock: 1,
            type: "SINGLE"
        },
        {
            name: "Acer Swift Go 14",
            sku: "AC-SWGO14-I7-16G",
            barcode: "471023000801",
            qrCode: "QR-SWGO14",
            categoryId: categoriesMap["Laptops"],
            brandId: brandsMap["Acer"],
            model: "Swift Go 14",
            color: "Olive Gold",
            storage: "512GB SSD",
            ram: "16GB",
            processor: "Intel Core i7-13700H",
            warrantyMonths: 12,
            supplierId: supplierB.id,
            purchasePrice: 750.00,
            sellingPrice: 949.00,
            wholesalePrice: 820.00,
            taxRate: 10.0,
            discountRate: 5.0,
            images: JSON.stringify(["/placeholder_swgo14.jpg"]),
            description: "Lightweight and powerful ultrabook with OLED display option.",
            weight: 1.30,
            stockQuantity: 15,
            minStock: 5,
            type: "SINGLE"
        },
        // MONITORS
        {
            name: "LG UltraGear 27GP950-B",
            sku: "LG-27GP950-4K144",
            barcode: "195173000901",
            qrCode: "QR-27GP950",
            categoryId: categoriesMap["Monitors"],
            brandId: brandsMap["LG"],
            model: "UltraGear 27GP950-B",
            color: "Black",
            warrantyMonths: 36,
            supplierId: supplierB.id,
            purchasePrice: 550.00,
            sellingPrice: 749.00,
            wholesalePrice: 620.00,
            taxRate: 10.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_27gp950.jpg"]),
            description: "27-inch 4K 144Hz Nano IPS gaming monitor with HDMI 2.1.",
            weight: 6.80,
            stockQuantity: 10,
            minStock: 3,
            type: "SINGLE"
        },
        {
            name: "Samsung Odyssey G9 49\"",
            sku: "SM-ODG9-49-DQHD",
            barcode: "880609001001",
            qrCode: "QR-ODG9",
            categoryId: categoriesMap["Monitors"],
            brandId: brandsMap["Samsung"],
            model: "Odyssey G9 49\"",
            color: "Black/White",
            warrantyMonths: 36,
            supplierId: supplierA.id,
            purchasePrice: 1000.00,
            sellingPrice: 1299.00,
            wholesalePrice: 1100.00,
            taxRate: 10.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_odg9.jpg"]),
            description: "49-inch DQHD curved gaming monitor with 240Hz refresh rate.",
            weight: 14.50,
            stockQuantity: 6,
            minStock: 2,
            type: "SINGLE"
        },
        {
            name: "Dell UltraSharp U2723QE",
            sku: "DE-U2723QE-4K",
            barcode: "884116001101",
            qrCode: "QR-U2723",
            categoryId: categoriesMap["Monitors"],
            brandId: brandsMap["Dell"],
            model: "UltraSharp U2723QE",
            color: "Platinum Silver",
            warrantyMonths: 36,
            supplierId: supplierB.id,
            purchasePrice: 450.00,
            sellingPrice: 599.00,
            wholesalePrice: 500.00,
            taxRate: 10.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_u2723.jpg"]),
            description: "27-inch 4K IPS Black monitor with USB-C hub for productivity.",
            weight: 6.64,
            stockQuantity: 12,
            minStock: 4,
            type: "SINGLE"
        },
        // TVs
        {
            name: "LG C3 65\" OLED TV",
            sku: "LG-C3-65-OLED",
            barcode: "195173001201",
            qrCode: "QR-LGC3",
            categoryId: categoriesMap["TVs"],
            brandId: brandsMap["LG"],
            model: "OLED65C3PUA",
            color: "Dark Silver",
            warrantyMonths: 24,
            supplierId: supplierA.id,
            purchasePrice: 1400.00,
            sellingPrice: 1799.00,
            wholesalePrice: 1550.00,
            taxRate: 10.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_lgc3.jpg"]),
            description: "65-inch OLED evo TV with perfect blacks and AI processor.",
            weight: 23.00,
            stockQuantity: 8,
            minStock: 2,
            type: "SINGLE"
        },
        {
            name: "Samsung 75\" QN85B Neo QLED",
            sku: "SM-QN85B-75",
            barcode: "880609001301",
            qrCode: "QR-QN85B",
            categoryId: categoriesMap["TVs"],
            brandId: brandsMap["Samsung"],
            model: "QN75QN85BAFXZA",
            color: "Titan Black",
            warrantyMonths: 24,
            supplierId: supplierA.id,
            purchasePrice: 1200.00,
            sellingPrice: 1599.00,
            wholesalePrice: 1350.00,
            taxRate: 10.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_qn85b.jpg"]),
            description: "75-inch Neo QLED 4K TV with Quantum Matrix technology.",
            weight: 32.00,
            stockQuantity: 6,
            minStock: 2,
            type: "SINGLE"
        },
        {
            name: "Sony 55\" Bravia XR A95L QD-OLED",
            sku: "SO-A95L-55",
            barcode: "454873001401",
            qrCode: "QR-A95L",
            categoryId: categoriesMap["TVs"],
            brandId: brandsMap["Sony"],
            model: "XR-55A95L",
            color: "Dark Silver",
            warrantyMonths: 24,
            supplierId: supplierA.id,
            purchasePrice: 1600.00,
            sellingPrice: 1999.00,
            wholesalePrice: 1750.00,
            taxRate: 10.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_a95l.jpg"]),
            description: "55-inch QD-OLED TV with cognitive processor and Acoustic Surface Audio.",
            weight: 21.00,
            stockQuantity: 4,
            minStock: 1,
            type: "SINGLE"
        },
        // AUDIO
        {
            name: "Sony WH-1000XM5",
            sku: "SO-WH1000XM5-B",
            barcode: "454873000321",
            qrCode: "QR-XM5",
            categoryId: categoriesMap["Audio"],
            brandId: brandsMap["Sony"],
            model: "WH-1000XM5",
            color: "Black",
            warrantyMonths: 12,
            supplierId: supplierA.id,
            purchasePrice: 250.00,
            sellingPrice: 399.00,
            wholesalePrice: 300.00,
            taxRate: 5.0,
            discountRate: 10.0,
            images: JSON.stringify(["/placeholder_xm5.jpg"]),
            description: "Industry-leading noise cancelling wireless headphones.",
            weight: 0.25,
            stockQuantity: 40,
            minStock: 10,
            type: "SINGLE"
        },
        {
            name: "Bose QuietComfort Ultra Headphones",
            sku: "BOSE-QCUH-B",
            barcode: "017817000501",
            qrCode: "QR-QCUH",
            categoryId: categoriesMap["Audio"],
            brandId: brandsMap["Bose"],
            model: "QuietComfort Ultra Headphones",
            color: "Black",
            warrantyMonths: 24,
            supplierId: supplierA.id,
            purchasePrice: 280.00,
            sellingPrice: 429.00,
            wholesalePrice: 330.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_qcuh.jpg"]),
            description: "Bose's best noise cancelling headphones with Immersive Audio.",
            weight: 0.25,
            stockQuantity: 25,
            minStock: 8,
            type: "SINGLE"
        },
        {
            name: "JBL Charge 5",
            sku: "JBL-CHG5-BLUE",
            barcode: "692528100001",
            qrCode: "QR-CHG5",
            categoryId: categoriesMap["Audio"],
            brandId: brandsMap["JBL"],
            model: "Charge 5",
            color: "Blue",
            warrantyMonths: 12,
            supplierId: supplierA.id,
            purchasePrice: 120.00,
            sellingPrice: 179.95,
            wholesalePrice: 140.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_chg5.jpg"]),
            description: "Portable Bluetooth speaker with deep bass and IP67 waterproof rating.",
            weight: 0.96,
            stockQuantity: 50,
            minStock: 15,
            type: "SINGLE"
        },
        {
            name: "JBL Flip 6",
            sku: "JBL-FLIP6-RED",
            barcode: "692528100002",
            qrCode: "QR-FLIP6",
            categoryId: categoriesMap["Audio"],
            brandId: brandsMap["JBL"],
            model: "Flip 6",
            color: "Red",
            warrantyMonths: 12,
            supplierId: supplierA.id,
            purchasePrice: 80.00,
            sellingPrice: 119.95,
            wholesalePrice: 95.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_flip6.jpg"]),
            description: "Portable waterproof Bluetooth speaker with JBL Pro Sound.",
            weight: 0.55,
            stockQuantity: 60,
            minStock: 20,
            type: "SINGLE"
        },
        {
            name: "Sennheiser Momentum 4 Wireless",
            sku: "SEN-MM4-B",
            barcode: "404418600001",
            qrCode: "QR-MM4",
            categoryId: categoriesMap["Audio"],
            brandId: brandsMap["Sennheiser"],
            model: "Momentum 4 Wireless",
            color: "Black",
            warrantyMonths: 24,
            supplierId: supplierB.id,
            purchasePrice: 220.00,
            sellingPrice: 349.00,
            wholesalePrice: 260.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_mm4.jpg"]),
            description: "Premium wireless headphones with 60-hour battery and audiophile sound.",
            weight: 0.293,
            stockQuantity: 18,
            minStock: 5,
            type: "SINGLE"
        },
        {
            name: "Apple AirPods Pro 2 (USB-C)",
            sku: "AP-APP2-USBC",
            barcode: "190199000401",
            qrCode: "QR-APP2",
            categoryId: categoriesMap["Audio"],
            brandId: brandsMap["Apple"],
            model: "AirPods Pro 2",
            color: "White",
            warrantyMonths: 12,
            supplierId: supplierA.id,
            purchasePrice: 170.00,
            sellingPrice: 249.00,
            wholesalePrice: 195.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_app2.jpg"]),
            description: "Apple's premium wireless earbuds with adaptive audio and USB-C.",
            weight: 0.0508,
            stockQuantity: 60,
            minStock: 20,
            type: "SINGLE"
        },
        {
            name: "Samsung Galaxy Buds2 Pro",
            sku: "SM-GB2P-B",
            barcode: "880609001501",
            qrCode: "QR-GB2P",
            categoryId: categoriesMap["Audio"],
            brandId: brandsMap["Samsung"],
            model: "Galaxy Buds2 Pro",
            color: "Graphite",
            warrantyMonths: 12,
            supplierId: supplierA.id,
            purchasePrice: 120.00,
            sellingPrice: 189.00,
            wholesalePrice: 140.00,
            taxRate: 5.0,
            discountRate: 10.0,
            images: JSON.stringify(["/placeholder_gb2p.jpg"]),
            description: "Samsung's premium earbuds with 360 Audio and ANC.",
            weight: 0.055,
            stockQuantity: 40,
            minStock: 12,
            type: "SINGLE"
        },
        // GAMING CONSOLES & ACCESSORIES
        {
            name: "PlayStation 5 Slim",
            sku: "SONY-PS5-SLIM",
            barcode: "454873001601",
            qrCode: "QR-PS5S",
            categoryId: categoriesMap["Gaming"],
            brandId: brandsMap["Sony"],
            model: "PlayStation 5 Slim",
            color: "White",
            warrantyMonths: 12,
            supplierId: supplierA.id,
            purchasePrice: 400.00,
            sellingPrice: 499.00,
            wholesalePrice: 440.00,
            taxRate: 8.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_ps5.jpg"]),
            description: "Slimmer PS5 with 1TB SSD and disc drive.",
            weight: 3.20,
            stockQuantity: 20,
            minStock: 5,
            type: "SINGLE"
        },
        {
            name: "Xbox Series X",
            sku: "MS-XSX-1TB",
            barcode: "889842001701",
            qrCode: "QR-XSX",
            categoryId: categoriesMap["Gaming"],
            brandId: brandsMap["MSI"],
            model: "Xbox Series X",
            color: "Black",
            warrantyMonths: 12,
            supplierId: supplierA.id,
            purchasePrice: 400.00,
            sellingPrice: 499.00,
            wholesalePrice: 440.00,
            taxRate: 8.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_xsx.jpg"]),
            description: "Microsoft's most powerful console with 4K gaming at 120fps.",
            weight: 4.45,
            stockQuantity: 15,
            minStock: 4,
            type: "SINGLE"
        },
        {
            name: "Nintendo Switch OLED",
            sku: "NIN-SWOLED-W",
            barcode: "045496880001",
            qrCode: "QR-SWOLED",
            categoryId: categoriesMap["Gaming"],
            brandId: brandsMap["Sony"],
            model: "Nintendo Switch OLED",
            color: "White",
            warrantyMonths: 12,
            supplierId: supplierA.id,
            purchasePrice: 280.00,
            sellingPrice: 349.00,
            wholesalePrice: 310.00,
            taxRate: 8.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_swoled.jpg"]),
            description: "Nintendo Switch with vibrant 7-inch OLED screen.",
            weight: 0.42,
            stockQuantity: 25,
            minStock: 8,
            type: "SINGLE"
        },
        {
            name: "Razer DeathAdder V3",
            sku: "RAZ-DAV3-B",
            barcode: "840272001801",
            qrCode: "QR-DAV3",
            categoryId: categoriesMap["Gaming"],
            brandId: brandsMap["Razer"],
            model: "DeathAdder V3",
            color: "Black",
            warrantyMonths: 24,
            supplierId: supplierB.id,
            purchasePrice: 50.00,
            sellingPrice: 89.99,
            wholesalePrice: 60.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_dav3.jpg"]),
            description: "Ergonomic gaming mouse with Focus Pro 30K sensor.",
            weight: 0.059,
            stockQuantity: 45,
            minStock: 15,
            type: "SINGLE"
        },
        {
            name: "Corsair K100 RGB",
            sku: "COR-K100-MX",
            barcode: "840006601901",
            qrCode: "QR-K100",
            categoryId: categoriesMap["Gaming"],
            brandId: brandsMap["Corsair"],
            model: "K100 RGB",
            color: "Black",
            warrantyMonths: 24,
            supplierId: supplierB.id,
            purchasePrice: 160.00,
            sellingPrice: 229.99,
            wholesalePrice: 180.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_k100.jpg"]),
            description: "Premium mechanical gaming keyboard with OPX switches and iCUE.",
            weight: 1.32,
            stockQuantity: 20,
            minStock: 6,
            type: "SINGLE"
        },
        {
            name: "SteelSeries Arctis Nova Pro Wireless",
            sku: "SS-ANP-B",
            barcode: "810002002001",
            qrCode: "QR-ANP",
            categoryId: categoriesMap["Gaming"],
            brandId: brandsMap["SteelSeries"],
            model: "Arctis Nova Pro Wireless",
            color: "Black",
            warrantyMonths: 24,
            supplierId: supplierB.id,
            purchasePrice: 250.00,
            sellingPrice: 349.99,
            wholesalePrice: 280.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_anp.jpg"]),
            description: "Premium wireless gaming headset with hot-swappable battery and ANC.",
            weight: 0.338,
            stockQuantity: 15,
            minStock: 5,
            type: "SINGLE"
        },
        {
            name: "HyperX Cloud III Wireless",
            sku: "HX-CLOUD3W-B",
            barcode: "824296002101",
            qrCode: "QR-CLOUD3W",
            categoryId: categoriesMap["Gaming"],
            brandId: brandsMap["HyperX"],
            model: "Cloud III Wireless",
            color: "Black",
            warrantyMonths: 24,
            supplierId: supplierB.id,
            purchasePrice: 120.00,
            sellingPrice: 169.99,
            wholesalePrice: 135.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_cloud3w.jpg"]),
            description: "Lightweight wireless gaming headset with DTS Headphone:X.",
            weight: 0.330,
            stockQuantity: 25,
            minStock: 8,
            type: "SINGLE"
        },
        // WEARABLES
        {
            name: "Apple Watch Ultra 2",
            sku: "AP-AWU2-49MM",
            barcode: "190199000501",
            qrCode: "QR-AWU2",
            categoryId: categoriesMap["Wearables"],
            brandId: brandsMap["Apple"],
            model: "Apple Watch Ultra 2",
            color: "Titanium",
            warrantyMonths: 12,
            supplierId: supplierA.id,
            purchasePrice: 650.00,
            sellingPrice: 799.00,
            wholesalePrice: 700.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_awu2.jpg"]),
            description: "Most rugged and capable Apple Watch for extreme sports.",
            weight: 0.0614,
            stockQuantity: 15,
            minStock: 4,
            type: "SINGLE"
        },
        {
            name: "Samsung Galaxy Watch 6 Classic",
            sku: "SM-GW6C-47MM",
            barcode: "880609002201",
            qrCode: "QR-GW6C",
            categoryId: categoriesMap["Wearables"],
            brandId: brandsMap["Samsung"],
            model: "Galaxy Watch 6 Classic",
            color: "Black",
            warrantyMonths: 24,
            supplierId: supplierA.id,
            purchasePrice: 280.00,
            sellingPrice: 399.00,
            wholesalePrice: 320.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_gw6c.jpg"]),
            description: "Premium Samsung smartwatch with rotating bezel and health tracking.",
            weight: 0.059,
            stockQuantity: 20,
            minStock: 6,
            type: "SINGLE"
        },
        {
            name: "Garmin Fenix 7X Solar",
            sku: "GAR-F7XS-B",
            barcode: "753759002301",
            qrCode: "QR-F7XS",
            categoryId: categoriesMap["Wearables"],
            brandId: brandsMap["Garmin"],
            model: "Fenix 7X Solar",
            color: "Black",
            warrantyMonths: 24,
            supplierId: supplierB.id,
            purchasePrice: 550.00,
            sellingPrice: 749.99,
            wholesalePrice: 620.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_f7xs.jpg"]),
            description: "Solar-powered multisport GPS watch with advanced training metrics.",
            weight: 0.089,
            stockQuantity: 10,
            minStock: 3,
            type: "SINGLE"
        },
        {
            name: "Fitbit Charge 6",
            sku: "FB-C6-B",
            barcode: "810043002401",
            qrCode: "QR-C6",
            categoryId: categoriesMap["Wearables"],
            brandId: brandsMap["Fitbit"],
            model: "Charge 6",
            color: "Black",
            warrantyMonths: 12,
            supplierId: supplierA.id,
            purchasePrice: 100.00,
            sellingPrice: 159.95,
            wholesalePrice: 115.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_c6.jpg"]),
            description: "Advanced fitness tracker with Google integration and built-in GPS.",
            weight: 0.037,
            stockQuantity: 30,
            minStock: 10,
            type: "SINGLE"
        },
        // CAMERAS
        {
            name: "Sony Alpha A7 IV",
            sku: "SO-A7IV-B",
            barcode: "454873002501",
            qrCode: "QR-A7IV",
            categoryId: categoriesMap["Cameras"],
            brandId: brandsMap["Sony"],
            model: "Alpha A7 IV",
            color: "Black",
            warrantyMonths: 24,
            supplierId: supplierB.id,
            purchasePrice: 1800.00,
            sellingPrice: 2498.00,
            wholesalePrice: 2000.00,
            taxRate: 8.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_a7iv.jpg"]),
            description: "33MP full-frame mirrorless camera with real-time AF and 4K 60p.",
            weight: 0.658,
            stockQuantity: 8,
            minStock: 2,
            type: "SINGLE"
        },
        {
            name: "Canon EOS R6 Mark II",
            sku: "CA-R6MII-B",
            barcode: "454929002601",
            qrCode: "QR-R6MII",
            categoryId: categoriesMap["Cameras"],
            brandId: brandsMap["Canon"],
            model: "EOS R6 Mark II",
            color: "Black",
            warrantyMonths: 24,
            supplierId: supplierB.id,
            purchasePrice: 1800.00,
            sellingPrice: 2499.00,
            wholesalePrice: 2000.00,
            taxRate: 8.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_r6mii.jpg"]),
            description: "24.2MP full-frame camera with up to 40fps continuous shooting.",
            weight: 0.670,
            stockQuantity: 6,
            minStock: 2,
            type: "SINGLE"
        },
        {
            name: "GoPro Hero 12 Black",
            sku: "GP-HERO12-B",
            barcode: "194862002701",
            qrCode: "QR-HERO12",
            categoryId: categoriesMap["Cameras"],
            brandId: brandsMap["GoPro"],
            model: "Hero 12 Black",
            color: "Black",
            warrantyMonths: 12,
            supplierId: supplierA.id,
            purchasePrice: 300.00,
            sellingPrice: 399.99,
            wholesalePrice: 340.00,
            taxRate: 8.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_hero12.jpg"]),
            description: "Waterproof action camera with HyperSmooth 6.0 and 5.3K video.",
            weight: 0.154,
            stockQuantity: 20,
            minStock: 6,
            type: "SINGLE"
        },
        {
            name: "Nikon Z8",
            sku: "NIK-Z8-B",
            barcode: "018208002801",
            qrCode: "QR-Z8",
            categoryId: categoriesMap["Cameras"],
            brandId: brandsMap["Nikon"],
            model: "Z8",
            color: "Black",
            warrantyMonths: 24,
            supplierId: supplierB.id,
            purchasePrice: 2700.00,
            sellingPrice: 3696.00,
            wholesalePrice: 3000.00,
            taxRate: 8.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_z8.jpg"]),
            description: "45.7MP stacked sensor mirrorless camera with 20fps burst shooting.",
            weight: 0.910,
            stockQuantity: 4,
            minStock: 1,
            type: "SINGLE"
        },
        // ACCESSORIES
        {
            name: "Anker Nano II 65W Charger",
            sku: "ANK-N2-65W",
            barcode: "194644002901",
            qrCode: "QR-N2-65W",
            categoryId: categoriesMap["Chargers"],
            brandId: brandsMap["Anker"],
            model: "Nano II 65W",
            color: "White",
            warrantyMonths: 24,
            supplierId: supplierA.id,
            purchasePrice: 25.00,
            sellingPrice: 39.99,
            wholesalePrice: 30.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_n2-65w.jpg"]),
            description: "Compact GaN charger with USB-C PD 3.0 for laptops and phones.",
            weight: 0.116,
            stockQuantity: 80,
            minStock: 25,
            type: "SINGLE"
        },
        {
            name: "Anker 737 Power Bank 24000mAh",
            sku: "ANK-737-24K",
            barcode: "194644003001",
            qrCode: "QR-737",
            categoryId: categoriesMap["Power Banks"],
            brandId: brandsMap["Anker"],
            model: "737 Power Bank",
            color: "Black",
            warrantyMonths: 24,
            supplierId: supplierA.id,
            purchasePrice: 80.00,
            sellingPrice: 109.99,
            wholesalePrice: 90.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_737.jpg"]),
            description: "24000mAh power bank with 140W max output and smart display.",
            weight: 0.630,
            stockQuantity: 30,
            minStock: 10,
            type: "SINGLE"
        },
        {
            name: "Logitech MX Master 3S",
            sku: "LOG-MXM3S-B",
            barcode: "099395003101",
            qrCode: "QR-MXM3S",
            categoryId: categoriesMap["Accessories"],
            brandId: brandsMap["Logitech"],
            model: "MX Master 3S",
            color: "Graphite",
            warrantyMonths: 24,
            supplierId: supplierB.id,
            purchasePrice: 70.00,
            sellingPrice: 99.99,
            wholesalePrice: 80.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_mxm3s.jpg"]),
            description: "Premium wireless mouse with MagSpeed scroll and quiet clicks.",
            weight: 0.141,
            stockQuantity: 35,
            minStock: 10,
            type: "SINGLE"
        },
        {
            name: "Logitech MX Keys S",
            sku: "LOG-MXKS-B",
            barcode: "099395003201",
            qrCode: "QR-MXKS",
            categoryId: categoriesMap["Accessories"],
            brandId: brandsMap["Logitech"],
            model: "MX Keys S",
            color: "Graphite",
            warrantyMonths: 24,
            supplierId: supplierB.id,
            purchasePrice: 80.00,
            sellingPrice: 109.99,
            wholesalePrice: 90.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_mxks.jpg"]),
            description: "Advanced wireless keyboard with smart illumination and Perfect Stroke keys.",
            weight: 0.710,
            stockQuantity: 25,
            minStock: 8,
            type: "SINGLE"
        },
        {
            name: "Apple MagSafe Charger",
            sku: "AP-MS-CHG",
            barcode: "190199000601",
            qrCode: "QR-MSCHG",
            categoryId: categoriesMap["Chargers"],
            brandId: brandsMap["Apple"],
            model: "MagSafe Charger",
            color: "White",
            warrantyMonths: 12,
            supplierId: supplierA.id,
            purchasePrice: 30.00,
            sellingPrice: 39.00,
            wholesalePrice: 33.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_mschg.jpg"]),
            description: "Wireless charger with MagSafe alignment for iPhone.",
            weight: 0.044,
            stockQuantity: 50,
            minStock: 15,
            type: "SINGLE"
        },
        {
            name: "Samsung 25W Super Fast Charger",
            sku: "SM-25W-CHG",
            barcode: "880609003301",
            qrCode: "QR-SM25W",
            categoryId: categoriesMap["Chargers"],
            brandId: brandsMap["Samsung"],
            model: "25W Super Fast Charger",
            color: "White",
            warrantyMonths: 12,
            supplierId: supplierA.id,
            purchasePrice: 15.00,
            sellingPrice: 24.99,
            wholesalePrice: 18.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_sm25w.jpg"]),
            description: "25W USB-C super fast charger for Samsung Galaxy devices.",
            weight: 0.052,
            stockQuantity: 60,
            minStock: 20,
            type: "SINGLE"
        },
        // STORAGE
        {
            name: "Samsung T7 Shield 2TB",
            sku: "SM-T7S-2TB",
            barcode: "880609003401",
            qrCode: "QR-T7S",
            categoryId: categoriesMap["Storage"],
            brandId: brandsMap["Samsung"],
            model: "T7 Shield 2TB",
            color: "Black",
            warrantyMonths: 36,
            supplierId: supplierA.id,
            purchasePrice: 130.00,
            sellingPrice: 179.99,
            wholesalePrice: 145.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_t7s.jpg"]),
            description: "Rugged portable SSD with IP65 rating and 1050MB/s read speed.",
            weight: 0.098,
            stockQuantity: 25,
            minStock: 8,
            type: "SINGLE"
        },
        {
            name: "Western Digital Black SN850X 2TB",
            sku: "WD-SN850X-2TB",
            barcode: "718037003501",
            qrCode: "QR-SN850X",
            categoryId: categoriesMap["Storage"],
            brandId: brandsMap["Western Digital"],
            model: "Black SN850X 2TB",
            color: "Black",
            warrantyMonths: 60,
            supplierId: supplierB.id,
            purchasePrice: 120.00,
            sellingPrice: 159.99,
            wholesalePrice: 135.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_sn850x.jpg"]),
            description: "High-performance NVMe SSD with 7300MB/s read for gaming.",
            weight: 0.008,
            stockQuantity: 30,
            minStock: 10,
            type: "SINGLE"
        },
        {
            name: "Seagate Backup Plus Hub 8TB",
            sku: "SG-BPH-8TB",
            barcode: "763649003601",
            qrCode: "QR-BPH",
            categoryId: categoriesMap["Storage"],
            brandId: brandsMap["Seagate"],
            model: "Backup Plus Hub 8TB",
            color: "Black",
            warrantyMonths: 36,
            supplierId: supplierB.id,
            purchasePrice: 130.00,
            sellingPrice: 179.99,
            wholesalePrice: 145.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_bph.jpg"]),
            description: "Desktop external HDD with USB hub and 8TB storage capacity.",
            weight: 0.920,
            stockQuantity: 15,
            minStock: 5,
            type: "SINGLE"
        },
        // NETWORKING
        {
            name: "TP-Link Archer AX73",
            sku: "TP-AX73",
            barcode: "693536400001",
            qrCode: "QR-AX73",
            categoryId: categoriesMap["Networking"],
            brandId: brandsMap["TP-Link"],
            model: "Archer AX73",
            color: "Black",
            warrantyMonths: 36,
            supplierId: supplierA.id,
            purchasePrice: 120.00,
            sellingPrice: 169.99,
            wholesalePrice: 135.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_ax73.jpg"]),
            description: "AX5400 dual-band WiFi 6 router with MU-MIMO and beamforming.",
            weight: 0.730,
            stockQuantity: 20,
            minStock: 6,
            type: "SINGLE"
        },
        {
            name: "Google Nest WiFi Pro (2-Pack)",
            sku: "GO-NWP-2PK",
            barcode: "194253003701",
            qrCode: "QR-NWP2",
            categoryId: categoriesMap["Networking"],
            brandId: brandsMap["Google"],
            model: "Nest WiFi Pro (2-Pack)",
            color: "Snow",
            warrantyMonths: 24,
            supplierId: supplierB.id,
            purchasePrice: 230.00,
            sellingPrice: 299.99,
            wholesalePrice: 260.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_nwp2.jpg"]),
            description: "Mesh WiFi 6E system covering up to 3300 sq ft with 2 pack.",
            weight: 0.907,
            stockQuantity: 12,
            minStock: 4,
            type: "SINGLE"
        },
        // COMPONENTS
        {
            name: "NVIDIA GeForce RTX 4070 Super",
            sku: "NV-4070S-12G",
            barcode: "843328003801",
            qrCode: "QR-4070S",
            categoryId: categoriesMap["Components"],
            brandId: brandsMap["NVIDIA"],
            model: "GeForce RTX 4070 Super",
            color: "Black",
            warrantyMonths: 36,
            supplierId: supplierB.id,
            purchasePrice: 480.00,
            sellingPrice: 599.99,
            wholesalePrice: 520.00,
            taxRate: 10.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_4070s.jpg"]),
            description: "12GB GDDR6X GPU with DLSS 3 and ray tracing for 1440p gaming.",
            weight: 1.090,
            stockQuantity: 10,
            minStock: 3,
            type: "SINGLE"
        },
        {
            name: "AMD Ryzen 9 7950X3D",
            sku: "AMD-R9-7950X3D",
            barcode: "100100003901",
            qrCode: "QR-7950X3D",
            categoryId: categoriesMap["Components"],
            brandId: brandsMap["AMD"],
            model: "Ryzen 9 7950X3D",
            color: "N/A",
            warrantyMonths: 36,
            supplierId: supplierB.id,
            purchasePrice: 550.00,
            sellingPrice: 699.99,
            wholesalePrice: 600.00,
            taxRate: 10.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_7950x3d.jpg"]),
            description: "16-core 3D V-Cache processor, king of gaming CPUs.",
            weight: 0.100,
            stockQuantity: 8,
            minStock: 2,
            type: "SINGLE"
        },
        {
            name: "Intel Core i9-14900K",
            sku: "INT-I9-14900K",
            barcode: "735858004001",
            qrCode: "QR-14900K",
            categoryId: categoriesMap["Components"],
            brandId: brandsMap["Intel"],
            model: "Core i9-14900K",
            color: "N/A",
            warrantyMonths: 36,
            supplierId: supplierB.id,
            purchasePrice: 480.00,
            sellingPrice: 589.99,
            wholesalePrice: 520.00,
            taxRate: 10.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_14900k.jpg"]),
            description: "24-core 32-thread desktop processor for ultimate performance.",
            weight: 0.120,
            stockQuantity: 10,
            minStock: 3,
            type: "SINGLE"
        },
        {
            name: "Corsair Vengeance DDR5 32GB (2x16GB)",
            sku: "COR-VDD5-32G",
            barcode: "840006604101",
            qrCode: "QR-VDD5",
            categoryId: categoriesMap["Components"],
            brandId: brandsMap["Corsair"],
            model: "Vengeance DDR5 32GB",
            color: "Black",
            warrantyMonths: 60,
            supplierId: supplierB.id,
            purchasePrice: 80.00,
            sellingPrice: 109.99,
            wholesalePrice: 90.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_vdd5.jpg"]),
            description: "32GB DDR5-5600MHz memory kit with tight timings for performance.",
            weight: 0.045,
            stockQuantity: 40,
            minStock: 12,
            type: "SINGLE"
        },
        // PRINTERS
        {
            name: "HP LaserJet Pro M404dn",
            sku: "HP-LJP-M404DN",
            barcode: "195201004201",
            qrCode: "QR-M404DN",
            categoryId: categoriesMap["Printers"],
            brandId: brandsMap["HP"],
            model: "LaserJet Pro M404dn",
            color: "White",
            warrantyMonths: 12,
            supplierId: supplierB.id,
            purchasePrice: 220.00,
            sellingPrice: 299.99,
            wholesalePrice: 250.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_m404dn.jpg"]),
            description: "Mono laser printer with duplex printing and 40ppm speed.",
            weight: 8.80,
            stockQuantity: 15,
            minStock: 5,
            type: "SINGLE"
        },
        {
            name: "Epson EcoTank L3250",
            sku: "EP-L3250",
            barcode: "010164004301",
            qrCode: "QR-L3250",
            categoryId: categoriesMap["Printers"],
            brandId: brandsMap["Epson"],
            model: "EcoTank L3250",
            color: "Black",
            warrantyMonths: 12,
            supplierId: supplierB.id,
            purchasePrice: 180.00,
            sellingPrice: 249.99,
            wholesalePrice: 200.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_l3250.jpg"]),
            description: "Ink tank printer with print, scan, copy and low running cost.",
            weight: 3.90,
            stockQuantity: 12,
            minStock: 4,
            type: "SINGLE"
        },
        // SMART HOME
        {
            name: "Amazon Echo Show 10",
            sku: "AMZ-ES10-3RD",
            barcode: "841667004401",
            qrCode: "QR-ES10",
            categoryId: categoriesMap["Smart Home"],
            brandId: brandsMap["Anker"],
            model: "Echo Show 10 (3rd Gen)",
            color: "Charcoal",
            warrantyMonths: 12,
            supplierId: supplierA.id,
            purchasePrice: 170.00,
            sellingPrice: 249.99,
            wholesalePrice: 195.00,
            taxRate: 5.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_es10.jpg"]),
            description: "10.1-inch HD smart display that rotates to follow you.",
            weight: 2.56,
            stockQuantity: 15,
            minStock: 5,
            type: "SINGLE"
        },
        {
            name: "Dyson V15 Detect Absolute",
            sku: "DY-V15D-ABS",
            barcode: "885609004501",
            qrCode: "QR-V15D",
            categoryId: categoriesMap["Home Appliances"],
            brandId: brandsMap["Dyson"],
            model: "V15 Detect Absolute",
            color: "Yellow/Nickel",
            warrantyMonths: 24,
            supplierId: supplierA.id,
            purchasePrice: 480.00,
            sellingPrice: 649.99,
            wholesalePrice: 540.00,
            taxRate: 10.0,
            discountRate: 0.0,
            images: JSON.stringify(["/placeholder_v15d.jpg"]),
            description: "Cordless vacuum with laser dust detection and LCD screen.",
            weight: 3.10,
            stockQuantity: 10,
            minStock: 3,
            type: "SINGLE"
        },
        // BUNDLES
        {
            name: "Samsung Galaxy S24 Bundle",
            sku: "SM-S24U-BUNDLE",
            barcode: "880609004601",
            qrCode: "QR-S24BUNDLE",
            categoryId: categoriesMap["Smartphones"],
            brandId: brandsMap["Samsung"],
            model: "Galaxy S24 Ultra + Buds + Watch",
            color: "Phantom Black",
            warrantyMonths: 24,
            supplierId: supplierA.id,
            purchasePrice: 1200.00,
            sellingPrice: 1549.00,
            wholesalePrice: 1350.00,
            taxRate: 8.0,
            discountRate: 10.0,
            images: JSON.stringify(["/placeholder_s24bundle.jpg"]),
            description: "Bundle: Galaxy S24 Ultra + Galaxy Buds2 Pro + Galaxy Watch6 Classic",
            weight: 0.500,
            stockQuantity: 10,
            minStock: 2,
            type: "MULTIPLE"
        }
    ];
    for (const prodData of products) {
        const prod = await prisma.product.create({
            data: prodData
        });
        // Distribute stock quantities to branches
        const showroomQty = Math.floor(prodData.stockQuantity * 0.4);
        const warehouseQty = prodData.stockQuantity - showroomQty;
        await prisma.branchStock.create({
            data: {
                branchId: showroom.id,
                productId: prod.id,
                quantity: showroomQty
            }
        });
        await prisma.branchStock.create({
            data: {
                branchId: warehouse.id,
                productId: prod.id,
                quantity: warehouseQty
            }
        });
        // Create initial stock movements
        await prisma.stockMovement.create({
            data: {
                productId: prod.id,
                quantity: prodData.stockQuantity,
                type: "IN",
                branchId: warehouse.id,
                notes: "Initial inventory migration import"
            }
        });
    }
    console.log("Products and stocks seeded.");
    // 9. Add mock Expenses
    await prisma.expense.createMany({
        data: [
            {
                category: "RENT",
                amount: 2500.00,
                date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // 5 days ago
                description: "July Storefront Rent",
                paymentMethod: "BANK_TRANSFER"
            },
            {
                category: "UTILITIES",
                amount: 450.00,
                date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
                description: "Electricity bill for June",
                paymentMethod: "CASH"
            }
        ]
    });
    // 10. Add sample Repair Job
    await prisma.repairJob.create({
        data: {
            deviceName: "MacBook Air M2",
            serialNumber: "FVFGH123ABCD",
            customerId: customer1.id,
            faultDescription: "Water damage, machine not power cycling.",
            technicianId: technician.id,
            status: "DIAGNOSING",
            repairCost: 0.0,
            serviceCharge: 150.0,
            notes: "Cleaned corrosion off logical board. Diagnostic test pending."
        }
    });
    console.log("Expenses and repairs seeded.");
    console.log("Database seeded successfully!");
}
main()
    .catch((e) => {
    console.error("Seeding failed: ", e);
    process.exit(1);
})
    .finally(async () => {
    await prisma.$disconnect();
});
